---
type: map
mapping:
    "tool_panel_section_label":
        type: str
        required: true

    "tools":
        type: seq
        sequence:
            - type: map
              mapping:
                "name":
                    type: str
                    required: true
                "owner":
                    type: str
                    required: true
